// categorias.js - Mapeamento de fornecedores para categorias
const mapeamentoCategorias = {
  "IFOOD": "Receitas IFOOD",
  "STONE PAGAMENTOS S.A.": "Seguro",
  "Stone Pagamentos S.A.": "Seguro",
  "BEM MAIS ALIMENTOS": "Ingredientes Frios",
  "Bem Mais Alimentos": "Ingredientes Frios",
  "BEM MAIS ALIMENTOS LTDA": "Ingredientes Frios",
  "COMERCIAL BARBANTE PAPEL LTDA": "Embalagem/Descartável",
  "Comercial Barbante Papel Ltda": "Embalagem/Descartável",
  "COMERCIAL BARBANTE PAPEL LTDA - EPP": "Embalagem/Descartável",
  "Comercial Barbante Papel Ltda - Epp": "Embalagem/Descartável",
  "FRIGALON COM ATACADISTA DE CAR": "Carnes",
  "Frigalon Com Atacadista de Car": "Carnes",
  "FRIGALON": "Carnes",
  "Frigalon": "Carnes",
  "CERVEJARIA HRX LTDA": "Chopp",
  "Cervejaria Hrx Ltda": "Chopp",
  "TRENTINI UTILIDADES DOMESTICAS LTDA.": "Material de Reposição",
  "Trentini Utilidades Domesticas Ltda.": "Material de Reposição",
  "COMERCIAL FANNY LTDA EPP": "Bebidas",
  "Comercial Fanny Ltda Epp": "Bebidas",
  "COMERCIAL FANNY LTDA": "Bebidas",
  "Comercial Fanny Ltda": "Bebidas",
  "TOK SUPER": "Ingredientes Secos",
  "Tok Super": "Ingredientes Secos",
  "YOUJI OIKAWA": "Aluguel",
  "Youji Oikawa": "Aluguel",
  "SYELLA DICK PINHEIRO": "Propaganda e Publicidade",
  "Syella Dick Pinheiro": "Propaganda e Publicidade",
  "ELCIO VENTURI": "Despesas Sócios",
  "Elcio Venturi": "Despesas Sócios",
  "SIDINEI CORREA": "Despesas Sócios",
  "Sidinei Correa": "Despesas Sócios",
  "BIO CONTROL CONTROLE PRAGAS": "Dedetização",
  "Bio Control Controle Pragas": "Dedetização",
  "VINO & TIGELLE CURITIBA LTDA": "Hortifruti",
  "Vino & Tigelle Curitiba Ltda": "Hortifruti",
  "MASTER HIGIENE E LIMPEZA": "Material de Limpeza/Higiene",
  "Master Higiene e Limpeza": "Material de Limpeza/Higiene",
  "MASTER HIGIENE E LIMPEZA LTDA": "Material de Limpeza/Higiene",
  "L M A MARTINS": "Consultoria/Assessoria",
  "L M A Martins": "Consultoria/Assessoria",
  "MIRABILI OFFICES": "Condomínio",
  "Mirabili Offices": "Condomínio",
  "COMP PARAN GAS COMP": "Gás",
  "Comp Paran Gas Comp": "Gás",
  "CORA SCD SA": "Contabilidade",
  "Cora Scd Sa": "Contabilidade",
  "CONNECT CONTABILIDADE LTDA": "Contabilidade",
  "Connect Contabilidade Ltda": "Contabilidade",
  "SANDRO ROGERIO DA LUZ": "Carnes",
  "Sandro Rogerio da Luz": "Carnes",
  "MUFFATO VAREJO": "Ingredientes Secos",
  "Muffato Varejo": "Ingredientes Secos",
  "IRMAOS MUFFATO CIA LTDA": "Ingredientes Secos",
  "Irmaos Muffato Cia Ltda": "Ingredientes Secos",
  "BLUMEN COMERCIO DE ALIMENTOS LTDA": "Ingredientes Frios",
  "Blumen Comercio de Alimentos Ltda": "Ingredientes Frios",
  "BANCO ITAU S/A": "Despesa Bancária",
  "Banco Itau S/A": "Despesa Bancária",
  "FABRICIO FIGUEIREDO DE SALES": "Artístico",
  "Fabricio Figueiredo de Sales": "Artístico",
  "LIGGA TELECOM 0106": "Telefone e TV a Cabo",
  "Ligga Telecom 0106": "Telefone e TV a Cabo",
  "GRAFICA SETE BELO LTDA": "Serviços Gráficos",
  "Grafica Sete Belo Ltda": "Serviços Gráficos",
  "APORTE ÉLCIO": "Imposto de Renda",
  "Aporte Élcío": "Imposto de Renda",
  "SOFTWAR": "Locação Equipamentos",
  "Softwar": "Locação Equipamentos",
  "FAMILIA LUZ COMERCIO DE CARNES LTDA": "Carnes",
  "Familia Luz Comercio de Carnes Ltda": "Carnes",
  "FAMILIA LUZ COMERCIO DE CARNES LTDA - ME": "Carnes",
  "Familia Luz Comercio de Carnes Ltda - Me": "Carnes",
  "LACTO MINAS COM DE FRIOS LTDA": "Ingredientes Frios",
  "Lacta Minas Com de Frios Ltda": "Ingredientes Frios",
  "COPEL DISTRIBUICAO S.A.": "Energia Elétrica",
  "Copel Distribuicao S.A.": "Energia Elétrica",
  "COPEL DISTRIBUICAO SA": "Energia Elétrica",
  "B BRASIL PR P L D LTDA": "Material de Limpeza/Higiene",
  "B Brasil Pr P L D Ltda": "Material de Limpeza/Higiene",
  "FORT BRASIL PRODUTOS DE LIMPEZA E DESCARTAV": "Material de Limpeza/Higiene",
  "Fort Brasil Produtos de Limpeza e Descartav": "Material de Limpeza/Higiene",
  "FORT BRASIL PRODUTOS DE LIMPEZ": "Material de Limpeza/Higiene",
  "RAFAELA C GALON COMERCIO DE CONGELADOS": "Ingredientes Frios",
  "Rafaela C Galon Comercio de Congelados": "Ingredientes Frios",
  "VESPER MICRO DESTILARIA": "Bebidas",
  "Vesper Micro Destilaria": "Bebidas",
  "VESPER MICRO DESTILARIA LTDA": "Bebidas",
  "SERVIÇOS GRÁFICOS": "Serviços Gráficos",
  "Serviços Gráficos": "Serviços Gráficos",
  "DINHO . WOSNIACK DISTRIBUICAO DE BEBIDAS LTDA": "Bebidas",
  "Dinho Wosniack Distribuicao de Bebidas Ltda": "Bebidas",
  "PILANDRO COMERCIO DE BEBIDAS EIRELI": "Bebidas",
  "Pilandro Comercio de Bebidas Eireli": "Bebidas",
  "PILANDRO COMERCIO DE BEBIDAS LTDA": "Bebidas",
  "I9PAY SREDE PETROSOL": "Combustível",
  "I9pay Srede Petrosol": "Combustível",
  "DE MARCHI PR COM ALM LTDA": "Hortifruti",
  "De Marchi Pr Com Alm Ltda": "Hortifruti",
  "DE MARCHI PARANA COMERCIO DE ALIMENTOS L": "Ingredientes Secos",
  "GOLD INDUSTRIA E COMERCIO LT": "Ingredientes Secos",
  "Gold Industria e Comercio Lt": "Ingredientes Secos",
  "MARIA C DOS SANTOS HORTIFRUTI": "Hortifruti",
  "Maria C dos Santos Hortifruti": "Hortifruti",
  "PAGGraficaSeteBelo": "Serviços Gráficos",
  "Pag*GraficaSeteBelo": "Serviços Gráficos",
  "J M I COMERCIO DE CARNES": "Carnes",
  "J M I Comercio de Carnes": "Carnes",
  "HELLO GRAF A G EIRELI ME": "Serviços Gráficos",
  "Hello Graf A G Eireli Me": "Serviços Gráficos",
  "HELLOGRAF SERVIÇOS S LTDA": "Serviços Gráficos",
  "Hellograf Serviços S Ltda": "Serviços Gráficos",
  "HELLOGRAF SERVICOS S LTDA": "Serviços Gráficos",
  "BASTARDS COMERCIO VAREJISTA LTDA . ME": "Chopp",
  "Bastards Comercio Varejista Ltda . Me": "Chopp",
  "CERVEJARIA IGNORUS LTDA": "Chopp",
  "Cervejaria Ignorus Ltda": "Chopp",
  "DALCOMUNI DUTRA E COLOGNESE ADVOGADOS": "Advogado",
  "Dalcomuni Dutra e Cologne Advocados": "Advogado",
  "MONTE SIAO COOPERATIVA DE ENERGIA": "Energia Elétrica",
  "Monte Siao Cooperativa de Energia": "Energia Elétrica",
  "ROBSON LUIZ GUTIERREZ": "Manutenção Predial",
  "Robson Luiz Gutierrez": "Manutenção Predial",
  "RODRIGO FERREIRA JUSTINO": "Propaganda e Publicidade",
  "Rodrigo Ferreira Justino": "Propaganda e Publicidade",
  "STAMPA FOOD D ALIMENTOS LTDA": "Ingredientes Secos",
  "Stampa Food D Alimentos Ltda": "Ingredientes Secos",
  "STAMPA FOOD DITRIBUIDORA DE ALIMENTOS LT": "Ingredientes Secos",
  "PRECISAO COMERCIO DE GEN ALIM LTDA": "Ingredientes Secos",
  "Precisao Comercio de Gen Alim Ltda": "Ingredientes Secos",
  "MAZINHO PESCADOS": "Ingredientes Frios",
  "Mazinho Pescados": "Ingredientes Frios",
  "FERNANDO WAH HOCK EPP": "Doces",
  "Fernando Wah Hock Epp": "Doces",
  "HAROLDO DE PAULA SOUZA JUNIOR": "Manutenção de Informática",
  "Haroldo de Paula Souza Junior": "Manutenção de Informática",
  "ARISTIDES L DE M GUIMARAES": "Ingredientes Frios",
  "Aristides L de M Guimaraes": "Ingredientes Frios",
  "CARLOS ALBERTO BETTEGA": "Manutenção Predial",
  "Carlos Alberto Bettega": "Manutenção Predial",
  "CURITIBA HONESTA EVENTOS LTDA": "Propaganda e Publicidade",
  "Curitiba Honesta Eventos Ltda": "Propaganda e Publicidade",
  "DOM CARAMELLE": "Doces",
  "Dom Caramelle": "Doces",
  "EDUARDO C F SAMPAIO": "Doces",
  "Eduardo C F Sampaio": "Doces",
  "FABI LUIZ BEZERRA BASTOS TECNOLOGIA EM SISTEMAS E": "Sistema Cenna",
  "Fabi Luiz Bezerra Bastos Tecnologia em Sistemas e": "Sistema Cenna",
  "FABIO LUIZ BEZERRA BASTOS TECNOLOGIA EM SISTEMAS E": "Sistema Cenna",
  "DIAMANT PAPELARIA": "Material de Escritório",
  "SUL MINAS QUEIJOS E FR": "Ingredientes Secos",
  "PAGSEGURO INTERNET INSTITUICAO DE PAGAME": "Ingredientes Secos",
  "CONFEITAR": "Doces",
  "CP COM DE EMBALAGENS": "Embalagem/Descartável",
  "MERCADOCE": "Doces",
  "PREF MUN CURITIBA-TRIBUTO": "DAS",
  "TS CAFES ESPECIAIS LTDA": "Ingredientes Secos",
  "MERCADO COMERCIO DE EMBALAGENS LTDA": "Embalagem/Descartável",
  "DISK EMBALAGENS": "Embalagem/Descartável",
  "BACCO SPIRIT": "Bebidas",
  "Bacco Spirit": "Bebidas",
  "EDUARDO WOLFRAM RULF": "Bebidas",
  "JUMBO COMERCIO DE": "Ingredientes Secos",
  "L.P. DE BORBA & CIA LTDA": "Manutenção Móveis e Utensílios",
  "PG TON QUERO ELIMA": "Ingredientes Secos",
  "GASTRONOMIA DONA HEL": "Outras despesas ADM",
  "POSTO CAMPEIRO": "Combustível",
  "PAGMarechal": "Ingredientes Secos",
  "PAGMaxPosto": "Combustível",
  "RHOMA PRODUTOS E EQUIP": "Manutenção de Equipamentos",
  "HAVAN BARIGUI CURITIBA": "Aquisição de Equipamentos",
  "PIX Marketplace": "Propaganda e Publicidade",
  "BIOS UPDATE INFORMATICA": "Manutenção de Informática",
  "Bios update Informatica": "Manutenção de Informática",
  "SUPERMERCADO WOLFE": "Ingredientes Secos",
  "ABEL BLUMENKRANTZ 84092432020": "Doces",
  "JUNTA COMERCIAL DO PARANA": "DAS",
  "AROMA CARNE COM DE ALIM LTDA": "Carnes",
  "CONTABILISTA": "Material de Escritório",
  "DOCE CENTER FERNANDO WA": "Doces",
  "HARMONIA DO PAO-P": "Ingredientes Secos",
  "RODINEI CORREA": "Free Lance/taxa",
  "EDILSON DOS SANTOS LONGATTI": "Doces",
  "FRANCIELE MARCAL DA SILVA": "Free Lance/taxa",
  "CRBS S A": "Bebidas",
  "Clarissa Nobre Carmona": "Free Lance/taxa",
  "CLARISSA NOBRE CARMONA": "Free Lance/taxa",
  "LUNAR CRISTINA SCHIAVINI NICODEM": "Free Lance/taxa",
  "Karina Almeida da Silva": "Free Lance/taxa",
  "ADEMIR VICENTE": "Manutenção Predial",
  "CIPRIA ESPECIARIAS": "Ingredientes Secos",
  "LEONARDO GUIMARAES LOPES DA SILVA": "Artístico",
  "51.665.191 LEONARDO GUIMARAES LOPES DA SILVA": "Artístico",
  "BIG FESTAS": "Embalagem/Descartável",
  "CONDOR CHAMPAGNAT": "Ingredientes Secos",
  "EMPORIO NIPPON AJI": "Ingredientes Secos",
  "WORK IN HOUSE SERVICOS ADMINISTRATIVOS L": "Manutenção Predial",
  "Hosana Cenna": "Free Lance/taxa",
  "HOSANA OLIVEIRA DA SILVA": "Free Lance/taxa",
  "ADRIANO CALHEIRO CALDAS": "Bebidas",
  "RONDINELLI ANTONIO GOBI": "Carnes",
  "LUIZ CARLOS BRAIDATTO JUNIOR": "Material de Reposição",
  "TORTORELLO": "Ingredientes Frios",
  "WEB COMERCE SISTEMAS DE GESTAO EMPRESARI": "Ingredientes Frios",
  "Raphael Feitoza Quarte Pereira": "Free Lance/taxa",
  "Sandro Duda": "Free Lance/taxa",
  "GINA ZEPHYRIN": "Free Lance/taxa",
  "Gina Zephyrin": "Free Lance/taxa",
  "Guyveny Robert Volcy": "Free Lance/taxa",
  "GUYVENY ROBERT VOLCY": "Free Lance/taxa",
  "Christoffer Lamor Batista": "Free Lance/taxa",
  "Cristiano De Castro": "Free Lance/taxa",
  "Kailany de Paula Lacerda": "Free Lance/taxa",
  "Joao Guilherme Rocha Mendes": "Free Lance/taxa",
  "GISELE ALVES PEREIRA MILANEZ 04536173951": "Free Lance/taxa",
  "Diego Moreira Florenzano": "Free Lance/taxa",
  "BRUNO DECKER MORAES DE ARAUJO": "Free Lance/taxa",
  "SAFIRA DE JESUS LIMA DE CARVALHO": "Free Lance/taxa",
  "Safira de Jesus Lima de Carvalho": "Free Lance/taxa",
  "SILVIO ALVES DE OLIVEIRA JUNIOR": "Free Lance/taxa",
  "Silvio Alves De Oliveira Junior": "Free Lance/taxa",
  "MARIA CLARA MORAES DE ARAUJO": "Free Lance/taxa",
  "MARIO CLARA MORAES DE ARAUJO": "Free Lance/taxa",
  "LUCIANE DA SILVA": "Free Lance/taxa",
  "FILIAL DE MARIA CLARA MORAES DE ARAUJO": "Free Lance/taxa",
  "RENAN HENRIQUE SANTOS SOUZA": "Artístico",
  "JOSE EDUARDO PEREIRA DEQUECH": "Artístico",
  "Jose Eduardo Pereira Dequech": "Artístico",
  "Gilberto Mendes Braga de Souza": "Artístico",
  "Facebook Ads": "Anúncio",
  "FACEBOOK ADS": "Anúncio",
  "Facebook ads": "Anúncio",
  "fb ads": "Anúncio",
  "FB ADS": "Anúncio",
  "SION COOPERATIVA DE ENERGIA": "Energia Elétrica",
  "HELLOGRAFF ARTES GRAFICAS LTDA": "Serviços Gráficos",
  "ADRIELLY GOMES PIRES 05121269927": "Artístico"
};

// Estrutura de organização do DRE
const estruturaDRE = {
  "Receitas": [
    "Receitas IFOOD",
    "Crédito/Débito/Pix",
    "Aporte Sócio"
  ],
  "Custos Diretos": [
    "Ingredientes Frios",
    "Ingredientes Secos",
    "Carnes",
    "Hortifruti",
    "Chopp",
    "Bebidas",
    "Doces",
    "Embalagem/Descartável"
  ],
  "Despesas de Vendas": [
    "Propaganda e Publicidade",
    "Anúncio",
    "Free Lance/taxa",
    "Artístico"
  ],
  "Despesas Administrativas": [
    "Material de Reposição",
    "Material de Limpeza/Higiene",
    "Manutenção Predial",
    "Manutenção de Informática",
    "Manutenção de Equipamentos",
    "Manutenção Móveis e Utensílios",
    "Sistema Cenna",
    "Material de Escritório",
    "Consultoria/Assessoria",
    "Contabilidade",
    "Advogado",
    "Locação Equipamentos",
    "Outras despesas ADM"
  ],
  "Despesas com Infraestrutura": [
    "Aluguel",
    "Condomínio",
    "Energia Elétrica",
    "Gás",
    "Telefone e TV a Cabo",
    "Serviços Gráficos",
    "Dedetização",
    "Seguro",
    "Aquisição de Equipamentos",
    "Combustível"
  ],
  "Despesas Financeiras": [
    "Despesa Bancária"
  ],
  "Despesas com Sócios": [
    "Despesas Sócios"
  ],
  "Impostos": [
    "Imposto de Renda",
    "DAS"
  ]
};